### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by frankgerhardt** [RaRe-Technologies/movie-plots-by-genre#1]
With Anaconda 2:

pip install cython gensim sklearn pandas matplotlib nltk pyemd
Requirement already satisfied (use --upgrade to upgrade): cython in /home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages
Collecting gensim
  Using cached gensim-0.12.4.tar.gz
Collecting sklearn
  Using cached sklearn-0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pandas in /home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): nltk in /home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages
Collecting pyemd
  Using cached pyemd-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4I4f0w/pyemd/setup.py", line 44, in <module>
        extensions = cythonize(extensions)
      File "/home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 758, in cythonize
        aliases=aliases)
      File "/home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 651, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/frank/Python/anaconda/2.0.1/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyemd/emd.pyx' doesn't match any files

And with Anaconda 3:

pip install cython gensim sklearn pandas matplotlib nltk pyemd
Requirement already satisfied (use --upgrade to upgrade): cython in /home/frank/bin/anaconda3/lib/python3.4/site-packages
Collecting gensim
  Using cached gensim-0.12.4.tar.gz
Collecting sklearn
  Using cached sklearn-0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pandas in /home/frank/bin/anaconda3/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /home/frank/bin/anaconda3/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): nltk in /home/frank/bin/anaconda3/lib/python3.4/site-packages
Collecting pyemd
  Using cached pyemd-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2inom4h3/pyemd/setup.py", line 44, in <module>
        extensions = cythonize(extensions)
      File "/home/frank/bin/anaconda3/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 758, in cythonize
        aliases=aliases)
      File "/home/frank/bin/anaconda3/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 651, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/frank/bin/anaconda3/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyemd/emd.pyx' doesn't match any files

How can I make the pip install work?

**Comment by piotrgiedziun** [comment]
There is a fix in github version, use command below instead.

`pip install "git+https://github.com/wmayner/pyemd@develop#egg=pyemd"`

**Comment by frankgerhardt** [comment]
Ok, that worked
